#!/bin/bash

set -e

### don't forget to mount /dev/sdaX /boot/efi

#pacman -S dosfstools efibootmgr
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=arch_grub --recheck --debug
grub-mkconfig -o /boot/grub/grub.cfg
